import os
import sys
import numpy as np
sys.path.append('C:\\Program Files\\Coreform Cubit 2022.11\\bin')
import cubit 
cubit.init(['cubit'])

cubit.cmd('brick x 100 y 130 z 5')
cubit.cmd('brick x 70 y 100 z 5')
cubit.cmd('subtract body 2 from body 1 ')
cubit.cmd('move volume 1 x 22.75 y 30.5 z 2.5')
cubit.cmd('webcut volume 1 with xplane offset 22.5')
cubit.cmd('webcut volume 1 with xplane offset 23')
cubit.cmd('merge all')

cubit.cmd('##create curved central stile')
cubit.cmd('##back surface')
cubit.cmd('create curve arc vertex 26 29  radius 10000 normal 0 0 1 ')
cubit.cmd('create curve arc vertex 43 48  radius 10000 normal 0 0 1 ')
cubit.cmd('create surface  101 97 102 91')
cubit.cmd('merge all')
cubit.cmd('##left surface')
cubit.cmd('create curve arc vertex 25 30 radius 10000 normal 0 0 1 ')
cubit.cmd('create surface 105 41 101 37')
cubit.cmd('merge all')
cubit.cmd('## right surface')
cubit.cmd('create curve arc vertex 44 47 radius 10000 normal 0 0 1 ')
cubit.cmd('create surface 71 109 75 102')
cubit.cmd('merge all')
cubit.cmd('##front surface ')
cubit.cmd('create surface 90 105 94 109')
cubit.cmd('##creating volume')
cubit.cmd('surface 47 copy ')
cubit.cmd('surface 49 copy')
cubit.cmd('create volume surface 53 54 56 55 57 58')
cubit.cmd('merge all')

cubit.cmd('##break up geometry of frame for meshing')
cubit.cmd('webcut volume 3 with plane normal to curve 30 distance 0 from vertex 21')
cubit.cmd('webcut volume 1 with plane normal to curve 35 distance 0 from vertex 23')
cubit.cmd('webcut volume 12 with plane normal to curve 30 distance 0 from vertex 17')
cubit.cmd('webcut volume 1 with plane normal to curve 35 distance 0 from vertex 19')
cubit.cmd('webcut volume 3 with plane normal to curve 130 distance 0 from vertex 21')
cubit.cmd('webcut volume 13 with plane normal to curve 135 distance 0 from vertex 23')
cubit.cmd('webcut volume 14 with plane normal to curve 143 distance 0 from vertex 17')
cubit.cmd('webcut volume 1 with plane normal to curve 156 distance 0 from vertex 19')
cubit.cmd('merge all')

cubit.cmd('delete volume 1 3 4 5 12 13 14 15 16 17 18 19')

cubit.cmd('##mesh')
cubit.cmd('surface all scheme map')
cubit.cmd('##stile tops and bottoms')
cubit.cmd('curve 90 94 interval 4')
cubit.cmd('##middle sides')
cubit.cmd('curve 105 115 interval 100')
cubit.cmd('mesh surface 56')
cubit.cmd('## sweep through z to mesh volume')
cubit.cmd('curve 25 interval 6')
cubit.cmd('volume 11 scheme sweep source surface 56  targe surface 53 ')
cubit.cmd('mesh volume 11')

cubit.cmd('# Build node and element sets')
cubit.cmd('# All nodes')
cubit.cmd('nodeset 1 volume 11')
cubit.cmd('nodeset 1 name "all_nset"')
cubit.cmd('# Backside nodeset')
cubit.cmd('nodeset 2 surface 1')
cubit.cmd('# Rightside nodeset')
cubit.cmd('nodeset 3 surface 2')
cubit.cmd('# Top nodeset')
cubit.cmd('nodeset 4 surface 47')
cubit.cmd('nodeset 4 name "top_nset"')
cubit.cmd('# Leftside nodeset')
cubit.cmd('nodeset 5 surface 4')
cubit.cmd('# Bottom nodeset')
cubit.cmd('nodeset 6 surface 49')
cubit.cmd('nodeset 6 name "bot_nset"')
cubit.cmd('# Top elements')
cubit.cmd('block 1 hex in face in surf 47')
cubit.cmd('Block 1 Element Type HEX20')
cubit.cmd('# Bottom elements')
cubit.cmd('block 2 hex in face in surf 49')
cubit.cmd('Block 2 Element Type HEX20')
cubit.cmd('# All other elements')
cubit.cmd('block 3 hex in vol all except hex in block 1 2')
cubit.cmd('Block 3 Element Type HEX20')

cubit.cmd('export abaqus "C:/Users/hokie/OneDrive - Johns Hopkins/Documents/JHU/Research/morphing wing/Abaqus/buckling/elastic_hex20/iter_10000/part_10000.inp" overwrite everything')

##high hex in vol all except hex in block 1 2
##block 2 hex in face in surf 47
